### ISSUE TITLE
nginx.conf not found

### ISSUE THREAD

**Issue by Aschen** [ahumaro/Grav-PHP-Nginx#1]
Error : 

``` bash
/etc/nginx/grav_conf.sh: line 15: /usr/share/nginx/html/nginx.conf: No such file or directory
2016/01/05 14:45:50 The command [/bin/sh -c /etc/nginx/grav_conf.sh] returned a non-zero code: 1
```

The location of the nginx.conf file has changed in getgrav/grav github repository.

The file is now located at `webserver-configs/nginx.conf`.

I have to update the Dockerfile to create the image :

``` bash
51     done < /usr/share/nginx/html/nginx.conf' >> /etc/nginx/grav_conf.sh
```

``` bash
51     done < /usr/share/nginx/html/webserver-configs/nginx.conf' >> /etc/nginx/grav_conf.sh
```

**Comment by ahumaro** [comment]
Hi. Thanks for the info. I have upgraded the project to use the new Phusion version 0.9.19 and Ubuntu 16.04.
I also updated all other components to be compatible with the new base system. All is working fine again.
